### PR TITLE
some things related to debugging

### PR DESCRIPTION
**Pull request by shimpe**

### CODE REVIEW

**Comment by brianlheim** [comment]
General stylistic comments. I am not interested in helping out too much with this project (I don't use SC that much nowadays so I would be terrible at giving tutorial advice) but I am glad to review once in a while!

- always capitalize SuperCollider as SuperCollider
- yall should pick a line length for this project and stick with it otherwise there will be pandemonium. whatever is being used here (100 columns?) looks fine to me
- use 'supercollider' after triple backticks to get syntax highlighting
- do you want to use 'Sclang' or 'SuperCollider' to refer to the language? second is more common usage IMO. either way be consistent
- double check your indentation and code style

**Comment by shimpe** [comment]
@brianlheim Thanks for reviewing. With respect to "double check your indentation and code style". Is there anything in particular that caught your attention?

**Comment by brianlheim** [comment]
Sure! I don't want to nitpick on code style, but I agree it should be at least as good as what is recommended in the style guide, and be consistent throughout.

**Comment by cianoc** [comment]
@shimpe - This is great! Thanks. I'm not sure whether the cookbook, or the intermediate tutorials are the best place for this. Honestly I can see the same content being written differently for both audiences. I may even pull in some of the pattern stuff and put it into the patterns tutorial. 

I plan to read this properly when I get a chance. So far I've only had a chance to skim it, so my response is a little skimpier than I'd like.

For the cookbook audience I think some of the content may need to be rewritten slightly. In particular I think headers need to be a lot more focused on - you gotta problem, let me show you how to fix it. You do a great job of that later on (for example the debugging patterns stuff) - I think the postln postcs stuff is harder to follow. There seems to be a lot of useful information in there, but it's hard to see how/when one would use some of it. If you can think of ways to improve it that would be great, otherwise we can merge it in and I can edit it at a later date.

One way you might rewrite that section is to focus on a broken piece of code and gradually show ways in which the bugs can be identified. You're sort of doing that anyway, and I think that would be a fantastic way to introduce your debugging ideas, and to communicate clearly the different tools for outputting to the postcs window.

'Printing intermediate results in complex expressions' - not sure what you're trying to say here. Can you clarify this?

**Code Examples**

I think you should show the post window output for most, if not all of these. When in doubt ask yourself if the reader could understand what you've written without running SuperCollider.

Also some of the code examples seem quite long. I think in general code examples should be only as long as they need to be to get the point across and no longer. It's very tempting to show every possible permutation, but it's not usually necessary. 

**Commit Messages**
In future if you could make your commit messages a little bit more descriptive that would be helpful. I'm often guilty of this myself, but I think 'first commit' is probably a little terse :)

**Comment by shimpe** [comment]
@cianoc 

In general, a thing I struggle with is to strike the right balance between making it easy enough and keeping it fast/interesting enough so as not to get too boring too fast. That is, deciding what is my target audience.

"I think you should show the post window output for most, if not all of these"

I think I did that for most, in the form of comments. A slight concern of mine is if one shows all the outcomes of all experiments and suggestions, users just read over it and it won't sink in - at least not as much as if one tries it hands on.

"Also some of the code examples seem quite long."

I'm not sure if you are referring to the s.waitForBoot that I try to include whenever it's useful. I know it's not custom to include these in tutorials and explanations, but by leaving it out one runs the risk of users forgetting/not knowing how to boot their server and getting no sound, getting frustrated, and giving up. I have to say I quite dislike examples that build on state created in previous examples, so I like examples to be completely self-contained.

"In future if you could make your commit messages a little bit more descriptive that would be helpful."
Sure! I should have known that :)

**Comment by cianoc** [comment]
I think for the patterns book we should probably aim for more of a reference (you're here because you have a problem - hence you're pretty motivated). For the tutorials probably more fast/interesting.

For the pattern book I would probably want to just show examples to clarify what is happening. Having to try out code to work out what it does when you're just looking for a reference is quite annoying. For example I personally find it quite frustrating in the API docs to see example code that I have to run in order to understand the example - which slows me down. On the other hand I agree with you on tutorials - it is important there that you try things out.

On the examples being long - it's more that each code block has quite a few different examples of what you're illustrating, and I just wonder if they're all necessary to communicate the point you're making? If there are that's fine.

I promise to look at your revisions sometime this week. I'm a little slammed at the moment so it won't be for a couple of days. Just don't want you think I'm ignoring you...

**Comment by cianoc** [comment]
Thanks for all your hard work on this. There's some great content in this.

**Pull request merged**
